services:
  sttbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sttbot
    restart: unless-stopped

    expose:
      - "2010"

    env_file:
      - .env

    volumes:
      - ./data:/app/data

    networks:
      - traefik-net

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.sttbot.rule=Host(`sttbot.tgbots.site`)"
      - "traefik.http.routers.sttbot.entrypoints=websecure"
      - "traefik.http.routers.sttbot.tls=true"
      - "traefik.http.routers.sttbot.tls.certresolver=cf"

      - "traefik.http.services.sttbot.loadbalancer.server.port=2010"
      - "traefik.http.routers.sttbot.service=sttbot"

networks:
  traefik-net:
    external: true
